# Generated by Django 4.0.4 on 2022-05-14 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=254)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=254)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('complemento', models.CharField(max_length=200)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.CharField(max_length=50)),
                ('observacoes', models.TextField(max_length=200)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormaPagto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
                ('parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_custo', models.FloatField(max_length=10)),
                ('valor_venda', models.FloatField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('nome_crianca', models.CharField(max_length=100)),
                ('dt_nasc_crianca', models.DateField()),
                ('medidas', models.CharField(max_length=200)),
                ('sexo', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('tamanho', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=50)),
                ('valor_custo', models.FloatField(max_length=10)),
                ('valor_venda', models.FloatField(max_length=10)),
                ('obs', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadoras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField()),
                ('data_entrega', models.DateField()),
                ('obs', models.TextField(max_length=255)),
                ('status', models.CharField(max_length=10)),
                ('valor_total_bruto', models.FloatField(max_length=10)),
                ('valor_frete', models.FloatField(max_length=10)),
                ('desconto', models.FloatField(max_length=10)),
                ('valor_total_liquido', models.FloatField(max_length=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.clientes')),
                ('forma_pagto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapagto')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('transportadora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportadoras')),
            ],
        ),
    ]
