# Generated by Django 4.0.4 on 2022-06-11 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.IntegerField()),
                ('nome', models.CharField(max_length=254)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('data_nascimento', models.DateField(null=True)),
                ('telefone', models.CharField(max_length=14, null=True)),
                ('email', models.CharField(max_length=254, null=True)),
                ('cep', models.CharField(max_length=8, null=True)),
                ('logradouro', models.CharField(max_length=60, null=True)),
                ('numero', models.CharField(max_length=10, null=True)),
                ('bairro', models.CharField(max_length=60, null=True)),
                ('complemento', models.CharField(max_length=200, null=True)),
                ('cidade', models.CharField(max_length=60, null=True)),
                ('uf', models.CharField(max_length=50, null=True)),
                ('observacoes', models.TextField(max_length=200, null=True)),
                ('ativo', models.BooleanField(default=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
                ('parcelas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item_pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_custo', models.FloatField(max_length=10)),
                ('valor_venda', models.FloatField(max_length=10)),
                ('quantidade', models.IntegerField(null=True)),
                ('nome_crianca', models.CharField(max_length=100)),
                ('dt_nasc_crianca', models.DateField(null=True)),
                ('medidas', models.CharField(max_length=200, null=True)),
                ('sexo', models.CharField(max_length=12, null=True)),
            ],
            options={
                'ordering': ['id_pedido'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=100)),
                ('tamanho', models.CharField(default='Único', max_length=50, null=True)),
                ('cor', models.CharField(max_length=50)),
                ('valor_custo', models.FloatField(max_length=10)),
                ('valor_venda', models.FloatField(max_length=10)),
                ('obs', models.TextField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_pedido', models.DateField(auto_now_add=True)),
                ('data_entrega', models.DateField()),
                ('obs', models.TextField(max_length=255, null=True)),
                ('valor_total_bruto', models.FloatField(max_length=10)),
                ('valor_frete', models.FloatField(max_length=10, null=True)),
                ('desconto', models.FloatField(max_length=10, null=True)),
                ('valor_total_liquido', models.FloatField(max_length=10)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='api.cliente')),
                ('forma_pagto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.formapagto')),
                ('produtos', models.ManyToManyField(related_name='pedidos', through='api.Item_pedido', to='api.produto')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.status')),
                ('transportadora_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.transportadora')),
            ],
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='id_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido', to='api.pedido'),
        ),
        migrations.AddField(
            model_name='item_pedido',
            name='id_produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_pedido', to='api.produto'),
        ),
    ]
